# coding: utf-8

# flake8: noqa

"""
    Sample Todo API

    Sample todo backend for a senior capstone class. Demonstrates CRUD, auth (Firebase), error handling, and database integration.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthApi",
    "MetaApi",
    "TodosApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HTTPValidationError",
    "LocationInner",
    "SignInRequest",
    "SignInResponse",
    "TodoCreate",
    "TodoOut",
    "TodoUpdate",
    "UserOut",
    "ValidationError",
]

# import apis into sdk package
from todo_api_client.api.auth_api import AuthApi as AuthApi
from todo_api_client.api.meta_api import MetaApi as MetaApi
from todo_api_client.api.todos_api import TodosApi as TodosApi

# import ApiClient
from todo_api_client.api_response import ApiResponse as ApiResponse
from todo_api_client.api_client import ApiClient as ApiClient
from todo_api_client.configuration import Configuration as Configuration
from todo_api_client.exceptions import OpenApiException as OpenApiException
from todo_api_client.exceptions import ApiTypeError as ApiTypeError
from todo_api_client.exceptions import ApiValueError as ApiValueError
from todo_api_client.exceptions import ApiKeyError as ApiKeyError
from todo_api_client.exceptions import ApiAttributeError as ApiAttributeError
from todo_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from todo_api_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from todo_api_client.models.location_inner import LocationInner as LocationInner
from todo_api_client.models.sign_in_request import SignInRequest as SignInRequest
from todo_api_client.models.sign_in_response import SignInResponse as SignInResponse
from todo_api_client.models.todo_create import TodoCreate as TodoCreate
from todo_api_client.models.todo_out import TodoOut as TodoOut
from todo_api_client.models.todo_update import TodoUpdate as TodoUpdate
from todo_api_client.models.user_out import UserOut as UserOut
from todo_api_client.models.validation_error import ValidationError as ValidationError

