# coding: utf-8

"""
    Sample Todo API

    Sample todo backend for a senior capstone class. Demonstrates CRUD, auth (Firebase), error handling, and database integration.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from todo_api_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_read_current_user_api_v1_auth_users_me_get(self) -> None:
        """Test case for read_current_user_api_v1_auth_users_me_get

        Get the current authenticated user
        """
        pass

    def test_signin_api_v1_auth_signin_post(self) -> None:
        """Test case for signin_api_v1_auth_signin_post

        Authenticate with a Firebase ID token
        """
        pass


if __name__ == '__main__':
    unittest.main()
