# coding: utf-8

"""
    Sample Todo API

    Sample todo backend for a senior capstone class. Demonstrates CRUD, auth (Firebase), error handling, and database integration.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from todo_api_client.models.sign_in_response import SignInResponse

class TestSignInResponse(unittest.TestCase):
    """SignInResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignInResponse:
        """Test SignInResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignInResponse`
        """
        model = SignInResponse()
        if include_optional:
            return SignInResponse(
                access_token = '',
                token_type = 'bearer',
                user = todo_api_client.models.user_out.UserOut(
                    id = '', 
                    email = '', )
            )
        else:
            return SignInResponse(
                access_token = '',
                user = todo_api_client.models.user_out.UserOut(
                    id = '', 
                    email = '', ),
        )
        """

    def testSignInResponse(self):
        """Test SignInResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
