# coding: utf-8

"""
    Sample Todo API

    Sample todo backend for a senior capstone class. Demonstrates CRUD, auth (Firebase), error handling, and database integration.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from todo_api_client.models.todo_update import TodoUpdate

class TestTodoUpdate(unittest.TestCase):
    """TodoUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TodoUpdate:
        """Test TodoUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TodoUpdate`
        """
        model = TodoUpdate()
        if include_optional:
            return TodoUpdate(
                title = '0',
                description = '',
                completed = True
            )
        else:
            return TodoUpdate(
        )
        """

    def testTodoUpdate(self):
        """Test TodoUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
