# coding: utf-8

"""
    Sample Todo API

    Sample todo backend for a senior capstone class. Demonstrates CRUD, auth (Firebase), error handling, and database integration.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from todo_api_client.api.todos_api import TodosApi


class TestTodosApi(unittest.TestCase):
    """TodosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TodosApi()

    def tearDown(self) -> None:
        pass

    def test_create_new_todo_api_v1_todos_post(self) -> None:
        """Test case for create_new_todo_api_v1_todos_post

        Create a todo
        """
        pass

    def test_delete_existing_todo_api_v1_todos_todo_id_delete(self) -> None:
        """Test case for delete_existing_todo_api_v1_todos_todo_id_delete

        Delete a todo by id
        """
        pass

    def test_read_all_todos_api_v1_todos_get(self) -> None:
        """Test case for read_all_todos_api_v1_todos_get

        List all todos
        """
        pass

    def test_read_todo_api_v1_todos_todo_id_get(self) -> None:
        """Test case for read_todo_api_v1_todos_todo_id_get

        Get a todo by id
        """
        pass

    def test_update_existing_todo_api_v1_todos_todo_id_put(self) -> None:
        """Test case for update_existing_todo_api_v1_todos_todo_id_put

        Update a todo by id
        """
        pass


if __name__ == '__main__':
    unittest.main()
