# coding: utf-8

"""
    Sample Todo API

    Sample todo backend for a senior capstone class. Demonstrates CRUD, auth (Firebase), error handling, and database integration.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from todo_api_client.models.sign_in_request import SignInRequest

class TestSignInRequest(unittest.TestCase):
    """SignInRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignInRequest:
        """Test SignInRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignInRequest`
        """
        model = SignInRequest()
        if include_optional:
            return SignInRequest(
                id_token = ''
            )
        else:
            return SignInRequest(
                id_token = '',
        )
        """

    def testSignInRequest(self):
        """Test SignInRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
