# coding: utf-8

"""
    Sample Todo API

    Sample todo backend for a senior capstone class. Demonstrates CRUD, auth (Firebase), error handling, and database integration.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from todo_api_client.api.meta_api import MetaApi


class TestMetaApi(unittest.TestCase):
    """MetaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetaApi()

    def tearDown(self) -> None:
        pass

    def test_health_health_get(self) -> None:
        """Test case for health_health_get

        Health check
        """
        pass


if __name__ == '__main__':
    unittest.main()
