/* tslint:disable */
/* eslint-disable */
/**
 * Sample Todo API
 * Sample todo backend for a senior capstone class. Demonstrates CRUD, auth (Firebase), error handling, and database integration.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface LocationInner {
}
/**
 * Body for /auth/signin: a Firebase ID token minted by the client.
 */
export interface SignInRequest {
    /**
     * Firebase ID token from the client\'s auth SDK
     */
    'id_token': string;
}
export interface SignInResponse {
    /**
     * Firebase ID token echoed back for the client
     */
    'access_token': string;
    'token_type'?: string;
    'user': UserOut;
}
export interface TodoCreate {
    'title': string;
    'description'?: string | null;
}
export interface TodoOut {
    'id': number;
    'title': string;
    'description'?: string | null;
    'completed': boolean;
    'owner_id': string;
    'created_at': string;
    'updated_at': string;
}
export interface TodoUpdate {
    'title'?: string | null;
    'description'?: string | null;
    'completed'?: boolean | null;
}
export interface UserOut {
    'id': string;
    'email'?: string | null;
}
export interface ValidationError {
    'loc': Array<LocationInner>;
    'msg': string;
    'type': string;
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the profile of the user identified by the Bearer token.
         * @summary Get the current authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readCurrentUserApiV1AuthUsersMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/auth/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Exchanges a Firebase ID token (minted by the client\'s Firebase SDK) for a local user record. The user is created on first sign-in. Returns the same token to be sent as `Authorization: Bearer <token>` on all protected routes.
         * @summary Authenticate with a Firebase ID token
         * @param {SignInRequest} signInRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signinApiV1AuthSigninPost: async (signInRequest: SignInRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signInRequest' is not null or undefined
            assertParamExists('signinApiV1AuthSigninPost', 'signInRequest', signInRequest)
            const localVarPath = `/api/v1/auth/signin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signInRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the profile of the user identified by the Bearer token.
         * @summary Get the current authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readCurrentUserApiV1AuthUsersMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readCurrentUserApiV1AuthUsersMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.readCurrentUserApiV1AuthUsersMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Exchanges a Firebase ID token (minted by the client\'s Firebase SDK) for a local user record. The user is created on first sign-in. Returns the same token to be sent as `Authorization: Bearer <token>` on all protected routes.
         * @summary Authenticate with a Firebase ID token
         * @param {SignInRequest} signInRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signinApiV1AuthSigninPost(signInRequest: SignInRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignInResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signinApiV1AuthSigninPost(signInRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signinApiV1AuthSigninPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Returns the profile of the user identified by the Bearer token.
         * @summary Get the current authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readCurrentUserApiV1AuthUsersMeGet(options?: RawAxiosRequestConfig): AxiosPromise<UserOut> {
            return localVarFp.readCurrentUserApiV1AuthUsersMeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Exchanges a Firebase ID token (minted by the client\'s Firebase SDK) for a local user record. The user is created on first sign-in. Returns the same token to be sent as `Authorization: Bearer <token>` on all protected routes.
         * @summary Authenticate with a Firebase ID token
         * @param {SignInRequest} signInRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signinApiV1AuthSigninPost(signInRequest: SignInRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignInResponse> {
            return localVarFp.signinApiV1AuthSigninPost(signInRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * Returns the profile of the user identified by the Bearer token.
     * @summary Get the current authenticated user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public readCurrentUserApiV1AuthUsersMeGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).readCurrentUserApiV1AuthUsersMeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Exchanges a Firebase ID token (minted by the client\'s Firebase SDK) for a local user record. The user is created on first sign-in. Returns the same token to be sent as `Authorization: Bearer <token>` on all protected routes.
     * @summary Authenticate with a Firebase ID token
     * @param {SignInRequest} signInRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public signinApiV1AuthSigninPost(signInRequest: SignInRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signinApiV1AuthSigninPost(signInRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MetaApi - axios parameter creator
 */
export const MetaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetaApi - functional programming interface
 */
export const MetaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MetaApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any | null; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MetaApi.healthHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MetaApi - factory interface
 */
export const MetaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MetaApiFp(configuration)
    return {
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any | null; }> {
            return localVarFp.healthHealthGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetaApi - object-oriented interface
 */
export class MetaApi extends BaseAPI {
    /**
     * 
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthHealthGet(options?: RawAxiosRequestConfig) {
        return MetaApiFp(this.configuration).healthHealthGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * TodosApi - axios parameter creator
 */
export const TodosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new todo belonging to the authenticated user.
         * @summary Create a todo
         * @param {TodoCreate} todoCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewTodoApiV1TodosPost: async (todoCreate: TodoCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'todoCreate' is not null or undefined
            assertParamExists('createNewTodoApiV1TodosPost', 'todoCreate', todoCreate)
            const localVarPath = `/api/v1/todos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(todoCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a todo. Returns 204 on success, 404 if not found.
         * @summary Delete a todo by id
         * @param {number} todoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteExistingTodoApiV1TodosTodoIdDelete: async (todoId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'todoId' is not null or undefined
            assertParamExists('deleteExistingTodoApiV1TodosTodoIdDelete', 'todoId', todoId)
            const localVarPath = `/api/v1/todos/{todo_id}`
                .replace('{todo_id}', encodeURIComponent(String(todoId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns every todo owned by the authenticated user.
         * @summary List all todos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readAllTodosApiV1TodosGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/todos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single todo if it exists and belongs to the user, else 404.
         * @summary Get a todo by id
         * @param {number} todoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readTodoApiV1TodosTodoIdGet: async (todoId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'todoId' is not null or undefined
            assertParamExists('readTodoApiV1TodosTodoIdGet', 'todoId', todoId)
            const localVarPath = `/api/v1/todos/{todo_id}`
                .replace('{todo_id}', encodeURIComponent(String(todoId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates the fields of a todo. Only non-null fields are changed; passing null leaves a field unchanged.
         * @summary Update a todo by id
         * @param {number} todoId 
         * @param {TodoUpdate} todoUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateExistingTodoApiV1TodosTodoIdPut: async (todoId: number, todoUpdate: TodoUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'todoId' is not null or undefined
            assertParamExists('updateExistingTodoApiV1TodosTodoIdPut', 'todoId', todoId)
            // verify required parameter 'todoUpdate' is not null or undefined
            assertParamExists('updateExistingTodoApiV1TodosTodoIdPut', 'todoUpdate', todoUpdate)
            const localVarPath = `/api/v1/todos/{todo_id}`
                .replace('{todo_id}', encodeURIComponent(String(todoId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(todoUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TodosApi - functional programming interface
 */
export const TodosApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TodosApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new todo belonging to the authenticated user.
         * @summary Create a todo
         * @param {TodoCreate} todoCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewTodoApiV1TodosPost(todoCreate: TodoCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TodoOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNewTodoApiV1TodosPost(todoCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TodosApi.createNewTodoApiV1TodosPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes a todo. Returns 204 on success, 404 if not found.
         * @summary Delete a todo by id
         * @param {number} todoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteExistingTodoApiV1TodosTodoIdDelete(todoId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteExistingTodoApiV1TodosTodoIdDelete(todoId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TodosApi.deleteExistingTodoApiV1TodosTodoIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns every todo owned by the authenticated user.
         * @summary List all todos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readAllTodosApiV1TodosGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TodoOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readAllTodosApiV1TodosGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TodosApi.readAllTodosApiV1TodosGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a single todo if it exists and belongs to the user, else 404.
         * @summary Get a todo by id
         * @param {number} todoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readTodoApiV1TodosTodoIdGet(todoId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TodoOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readTodoApiV1TodosTodoIdGet(todoId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TodosApi.readTodoApiV1TodosTodoIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates the fields of a todo. Only non-null fields are changed; passing null leaves a field unchanged.
         * @summary Update a todo by id
         * @param {number} todoId 
         * @param {TodoUpdate} todoUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateExistingTodoApiV1TodosTodoIdPut(todoId: number, todoUpdate: TodoUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TodoOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateExistingTodoApiV1TodosTodoIdPut(todoId, todoUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TodosApi.updateExistingTodoApiV1TodosTodoIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TodosApi - factory interface
 */
export const TodosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TodosApiFp(configuration)
    return {
        /**
         * Creates a new todo belonging to the authenticated user.
         * @summary Create a todo
         * @param {TodoCreate} todoCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewTodoApiV1TodosPost(todoCreate: TodoCreate, options?: RawAxiosRequestConfig): AxiosPromise<TodoOut> {
            return localVarFp.createNewTodoApiV1TodosPost(todoCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a todo. Returns 204 on success, 404 if not found.
         * @summary Delete a todo by id
         * @param {number} todoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteExistingTodoApiV1TodosTodoIdDelete(todoId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteExistingTodoApiV1TodosTodoIdDelete(todoId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns every todo owned by the authenticated user.
         * @summary List all todos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readAllTodosApiV1TodosGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<TodoOut>> {
            return localVarFp.readAllTodosApiV1TodosGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single todo if it exists and belongs to the user, else 404.
         * @summary Get a todo by id
         * @param {number} todoId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readTodoApiV1TodosTodoIdGet(todoId: number, options?: RawAxiosRequestConfig): AxiosPromise<TodoOut> {
            return localVarFp.readTodoApiV1TodosTodoIdGet(todoId, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates the fields of a todo. Only non-null fields are changed; passing null leaves a field unchanged.
         * @summary Update a todo by id
         * @param {number} todoId 
         * @param {TodoUpdate} todoUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateExistingTodoApiV1TodosTodoIdPut(todoId: number, todoUpdate: TodoUpdate, options?: RawAxiosRequestConfig): AxiosPromise<TodoOut> {
            return localVarFp.updateExistingTodoApiV1TodosTodoIdPut(todoId, todoUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TodosApi - object-oriented interface
 */
export class TodosApi extends BaseAPI {
    /**
     * Creates a new todo belonging to the authenticated user.
     * @summary Create a todo
     * @param {TodoCreate} todoCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createNewTodoApiV1TodosPost(todoCreate: TodoCreate, options?: RawAxiosRequestConfig) {
        return TodosApiFp(this.configuration).createNewTodoApiV1TodosPost(todoCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes a todo. Returns 204 on success, 404 if not found.
     * @summary Delete a todo by id
     * @param {number} todoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteExistingTodoApiV1TodosTodoIdDelete(todoId: number, options?: RawAxiosRequestConfig) {
        return TodosApiFp(this.configuration).deleteExistingTodoApiV1TodosTodoIdDelete(todoId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns every todo owned by the authenticated user.
     * @summary List all todos
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public readAllTodosApiV1TodosGet(options?: RawAxiosRequestConfig) {
        return TodosApiFp(this.configuration).readAllTodosApiV1TodosGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a single todo if it exists and belongs to the user, else 404.
     * @summary Get a todo by id
     * @param {number} todoId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public readTodoApiV1TodosTodoIdGet(todoId: number, options?: RawAxiosRequestConfig) {
        return TodosApiFp(this.configuration).readTodoApiV1TodosTodoIdGet(todoId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates the fields of a todo. Only non-null fields are changed; passing null leaves a field unchanged.
     * @summary Update a todo by id
     * @param {number} todoId 
     * @param {TodoUpdate} todoUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateExistingTodoApiV1TodosTodoIdPut(todoId: number, todoUpdate: TodoUpdate, options?: RawAxiosRequestConfig) {
        return TodosApiFp(this.configuration).updateExistingTodoApiV1TodosTodoIdPut(todoId, todoUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}



